import { useState, useEffect } from 'react';
import { 
  X, Save, Info, Package, Headset, Hammer, 
  Construction, Calculator, Globe, Tag, 
  ChevronRight, Box, Settings, HardDrive,
  AlertCircle, QrCode, Barcode, Printer, RefreshCw
} from 'lucide-react';
import { QRCodeSVG } from 'qrcode.react';
import JsBarcode from 'jsbarcode';
import { useRef } from 'react';
import { inventoryApi, financeApi } from '../../utils/api';
import { useCompany } from '../../context/CompanyContext';

interface Props {
  item?: any;
  onClose: () => void;
  onSave: () => void;
}

const NomenclatureMasterCard = ({ item, onClose, onSave }: Props) => {
  const { activeCompany } = useCompany();
  const [activeTab, setActiveTab] = useState<'GENERAL' | 'ACCOUNTING' | 'INVENTORY' | 'PROJECT' | 'CODE_QR'>('GENERAL');
  const [categories, setCategories] = useState<any[]>([]);
  const [accounts, setAccounts] = useState<any[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  
  const [formData, setFormData] = useState({
    name: item?.name || '',
    type: item?.type || 'TRADE_ITEM',
    sku: item?.sku || '',
    code: item?.code || '',
    categoryId: item?.subCategory?.categoryId || '',
    subCategoryId: item?.subCategoryId || '',
    uom: item?.uom || 'Ədəd',
    size: item?.size || '',
    currency: item?.currency || 'AZN',
    costingMethod: item?.costingMethod || 'FIFO',
    isStockItem: item?.isStockItem ?? true,
    isService: item?.isService ?? false,
    isWorkItem: item?.isWorkItem ?? false,
    isProjectRelated: item?.isProjectRelated ?? false,
    projectId: item?.projectId || '',
    stageId: item?.stageId || '',
    smetaCode: item?.smetaCode || '',
    workType: item?.workType || '',
    inventoryAccountId: item?.inventoryAccountId || '',
    cogsAccountId: item?.cogsAccountId || '',
    revenueAccountId: item?.revenueAccountId || '',
    barcodeValue: item?.barcodeValue || '',
    barcodeType: item?.barcodeType || 'CODE128',
    qrCodeValue: item?.qrCodeValue || '',
    isAutoGeneratedCode: item?.isAutoGeneratedCode ?? false,
    primaryScanCode: item?.primaryScanCode || 'BARCODE'
  });

  const [isCustomUom, setIsCustomUom] = useState(false);

  useEffect(() => {
    const fetchMetadata = async () => {
      if (!activeCompany) return;
      try {
        const [catRes, accRes] = await Promise.all([
          inventoryApi.getCategories(activeCompany.id),
          financeApi.getAccounts(activeCompany.id)
        ]);
        setCategories(catRes);
        setAccounts(accRes.data || accRes || []);

        // Auto-fill SKU if not editing
        if (!item) {
          const codes = await inventoryApi.getNextCodes(activeCompany.id);
          setFormData(prev => ({ ...prev, sku: codes.item }));
        }
      } catch (err) {
        console.error(err);
      }
    };
    fetchMetadata();
  }, [activeCompany?.id, item]);

  const currentCategory = categories.find(c => c.id === formData.categoryId);
  const availableSubCategories = currentCategory?.subCategories || [];

  // Logic: Set flags based on type
  useEffect(() => {
    const type = formData.type;
    const updates: Partial<typeof formData> = {};
    
    if (['SERVICE', 'WORK', 'CONSTRUCTION'].includes(type)) {
      updates.isStockItem = false;
      updates.isService = type === 'SERVICE';
      updates.isWorkItem = ['WORK', 'CONSTRUCTION'].includes(type);
      updates.costingMethod = 'FIFO'; // Services don't need costing logic like LIFO
    } else {
      updates.isStockItem = true;
      updates.isService = false;
      updates.isWorkItem = false;
    }

    if (type === 'CONSTRUCTION') {
      updates.isProjectRelated = true;
    }

    // Default Account Suggestions
    if (type === 'RAW_MATERIAL') updates.inventoryAccountId = accounts.find(a => a.code === '201')?.id;
    if (type === 'WIP') updates.inventoryAccountId = accounts.find(a => a.code === '202')?.id;
    if (type === 'FINISHED_GOOD') updates.inventoryAccountId = accounts.find(a => a.code === '204')?.id;
    if (type === 'TRADE_ITEM') updates.inventoryAccountId = accounts.find(a => a.code === '205')?.id;

    setFormData(prev => ({ ...prev, ...updates }));
  }, [formData.type, accounts.length]);

  const handleSave = async () => {
    if (!activeCompany) return;
    setIsLoading(true);
    try {
      const payload = { ...formData, companyId: activeCompany.id };
      if (item?.id) {
        await inventoryApi.updateItem(item.id, payload, activeCompany.id);
      } else {
        await inventoryApi.createItem(payload, activeCompany.id);
      }
      onSave();
    } catch (err: any) {
      alert(err.message);
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="fixed inset-0 bg-slate-900/40 backdrop-blur-xl z-[150] flex items-center justify-end p-0">
      <div className="bg-white dark:bg-slate-900 w-full max-w-4xl h-full shadow-2xl flex flex-col animate-in slide-in-from-right duration-300">
        
        {/* MODAL HEADER */}
        <div className="flex items-center justify-between px-10 py-8 border-b border-slate-100 dark:border-slate-800">
          <div className="flex items-center space-x-4">
             <div className="p-3 bg-indigo-50 dark:bg-indigo-900/30 text-indigo-600 rounded-2xl">
                {formData.type === 'SERVICE' ? <Headset /> : formData.type === 'WORK' ? <Hammer /> : formData.type === 'CONSTRUCTION' ? <Construction /> : <Package />}
             </div>
             <div>
                <h2 className="text-xl font-black text-slate-800 dark:text-white uppercase italic tracking-tight">{item ? 'Nomenklatura Redaktəsi' : 'Yeni Nomenklatura Kartı'}</h2>
                <span className="text-[10px] font-black text-slate-400 uppercase italic tracking-widest">{formData.sku || 'SKU TƏYİN EDİLMƏYİB'}</span>
             </div>
          </div>
          <button onClick={onClose} className="p-4 bg-slate-50 dark:bg-slate-800 text-slate-400 rounded-full hover:bg-rose-50 hover:text-rose-500 transition-all active:scale-90">
             <X className="w-6 h-6" />
          </button>
        </div>

        {/* TABS NAVIGATION */}
        <div className="flex bg-slate-50/50 dark:bg-slate-800/50 px-10 py-2 border-b border-slate-100 dark:border-slate-800">
           <button onClick={() => setActiveTab('GENERAL')} className={`px-6 py-3 text-[10px] font-black uppercase italic tracking-widest transition-all ${activeTab === 'GENERAL' ? 'text-indigo-600 border-b-2 border-indigo-600' : 'text-slate-400'}`}>Əsas Parametrlər</button>
           <button onClick={() => setActiveTab('ACCOUNTING')} className={`px-6 py-3 text-[10px] font-black uppercase italic tracking-widest transition-all ${activeTab === 'ACCOUNTING' ? 'text-indigo-600 border-b-2 border-indigo-600' : 'text-slate-400'}`}>Mühasibat Mapping</button>
           <button onClick={() => setActiveTab('INVENTORY')} className={`px-6 py-3 text-[10px] font-black uppercase italic tracking-widest transition-all ${activeTab === 'INVENTORY' ? 'text-indigo-600 border-b-2 border-indigo-600' : 'text-slate-400'}`}>Anbar & Costing</button>
           {formData.isProjectRelated && (
             <button onClick={() => setActiveTab('PROJECT')} className={`px-6 py-3 text-[10px] font-black uppercase italic tracking-widest transition-all ${activeTab === 'PROJECT' ? 'text-indigo-600 border-b-2 border-indigo-600' : 'text-slate-400'}`}>Tikinti / Layihə</button>
           )}
           <button onClick={() => setActiveTab('CODE_QR')} className={`px-6 py-3 text-[10px] font-black uppercase italic tracking-widest transition-all ${activeTab === 'CODE_QR' ? 'text-indigo-600 border-b-2 border-indigo-600' : 'text-slate-400'}`}>Barkod & QR Kod</button>
        </div>

        {/* FORM CONTENT */}
        <div className="flex-1 overflow-y-auto p-10">
           {activeTab === 'GENERAL' && (
             <div className="space-y-8 animate-in fade-in duration-300">
                <div className="grid grid-cols-2 gap-8">
                   <div className="col-span-2 space-y-3">
                      <label className="text-[10px] font-black text-slate-400 uppercase italic tracking-widest">Nomenklatura Tam Adı</label>
                      <input 
                        value={formData.name}
                        onChange={e => setFormData({...formData, name: e.target.value})}
                        className="w-full p-5 bg-slate-50 dark:bg-slate-800 border-none rounded-3xl text-sm font-black italic shadow-inner outline-none focus:ring-2 focus:ring-indigo-500/10 placeholder-slate-300" 
                        placeholder="Məs: Kafel Metlax Suvaq işləri"
                      />
                   </div>

                   <div className="space-y-3">
                      <label className="text-[10px] font-black text-rose-500 uppercase italic tracking-widest">Əsas Kateqoriya</label>
                      <select 
                        value={formData.categoryId}
                        onChange={e => {
                            const catId = e.target.value;
                            const cat = categories.find(c => c.id === catId);
                            setFormData({
                                ...formData, 
                                categoryId: catId, 
                                subCategoryId: '',
                                type: cat?.type || 'TRADE_ITEM'
                            });
                        }}
                        className="w-full p-5 bg-rose-50/30 dark:bg-slate-800 border-none rounded-3xl text-sm font-black italic shadow-inner outline-none focus:ring-2 focus:ring-rose-500/10 appearance-none"
                      >
                         <option value="">Seçin...</option>
                         {categories.map(cat => (
                            <option key={cat.id} value={cat.id}>{cat.name}</option>
                         ))}
                      </select>
                   </div>

                   <div className="space-y-3">
                      <label className="text-[10px] font-black text-slate-400 uppercase italic tracking-widest">Alt Kateqoriya</label>
                      <select 
                        disabled={!formData.categoryId}
                        value={formData.subCategoryId}
                        onChange={e => setFormData({...formData, subCategoryId: e.target.value})}
                        className="w-full p-5 bg-slate-50 dark:bg-slate-800 border-none rounded-3xl text-sm font-black italic shadow-inner outline-none disabled:opacity-50 appearance-none"
                      >
                         <option value="">{formData.categoryId ? 'Alt Kateqoriya Seçin...' : 'Əvvəlcə kateqoriya seçin'}</option>
                         {availableSubCategories.map((sub: any) => (
                            <option key={sub.id} value={sub.id}>{sub.name}</option>
                         ))}
                      </select>
                   </div>

                   <div className="space-y-3">
                      <label className="text-[10px] font-black text-slate-400 uppercase italic tracking-widest">Ölçü Vahidi</label>
                      <div className="flex space-x-2">
                        {isCustomUom ? (
                             <input 
                                value={formData.uom}
                                onChange={e => setFormData({...formData, uom: e.target.value})}
                                autoFocus
                                className="flex-1 p-5 bg-slate-50 dark:bg-slate-800 border-none rounded-3xl text-sm font-black italic shadow-inner outline-none focus:ring-2 focus:ring-indigo-500/10"
                                placeholder="Vahid yazın..."
                             />
                        ) : (
                            <select 
                                value={formData.uom}
                                onChange={e => {
                                    if (e.target.value === 'CUSTOM') {
                                        setIsCustomUom(true);
                                        setFormData({...formData, uom: ''});
                                    } else {
                                        setFormData({...formData, uom: e.target.value});
                                    }
                                }}
                                className="flex-1 p-5 bg-slate-50 dark:bg-slate-800 border-none rounded-3xl text-sm font-black italic shadow-inner outline-none appearance-none"
                            >
                                <option>Ədəd</option>
                                <option>Kq</option>
                                <option>Metr</option>
                                <option>Saat</option>
                                <option>m2</option>
                                <option>m3</option>
                                <option value="CUSTOM">Digər...</option>
                            </select>
                        )}
                        {isCustomUom && (
                            <button 
                                onClick={() => setIsCustomUom(false)}
                                className="p-5 bg-slate-100 dark:bg-slate-800 text-slate-400 rounded-3xl hover:text-indigo-600 transition-all font-black text-[10px] uppercase italic"
                            >
                                Siyahı
                            </button>
                        )}
                      </div>
                   </div>

                   <div className="space-y-3">
                      <label className="text-[10px] font-black text-slate-400 uppercase italic tracking-widest">Ölçüsü (Size)</label>
                      <input 
                        value={formData.size}
                        onChange={e => setFormData({...formData, size: e.target.value})}
                        className="w-full p-5 bg-slate-50 dark:bg-slate-800 border-none rounded-3xl text-sm font-black italic shadow-inner outline-none focus:ring-2 focus:ring-indigo-500/10" 
                        placeholder="Məs: 40x40, S, XL və s."
                      />
                   </div>

                   <div className="space-y-3">
                      <label className="text-[10px] font-black text-slate-400 uppercase italic tracking-widest">SKU / Barkod</label>
                      <input 
                        value={formData.sku}
                        onChange={e => setFormData({...formData, sku: e.target.value})}
                        className="w-full p-5 bg-slate-50 dark:bg-slate-800 border-none rounded-3xl text-sm font-black italic shadow-inner outline-none focus:ring-2 focus:ring-indigo-500/10" 
                        placeholder="Məs: SKU-123456"
                      />
                   </div>
                </div>
             </div>
           )}

            {activeTab === 'ACCOUNTING' && (
              <div className="space-y-8 animate-in fade-in duration-300">
                <div className="p-6 bg-indigo-50/50 dark:bg-indigo-900/10 rounded-3xl border border-dashed border-indigo-200 dark:border-indigo-800">
                   <div className="flex items-center space-x-3 mb-4">
                      <AlertCircle className="w-5 h-5 text-indigo-600" />
                      <span className="text-xs font-black text-indigo-600 uppercase italic">Mühasibat Məntiqi</span>
                   </div>
                   <p className="text-[11px] text-slate-500 font-bold uppercase tracking-tight italic leading-relaxed">
                      Sistem avtomatik olaraq nomenklatura tipinə görə rəsmi mühasibat hesablarını (201, 204, 205, 601, 701) təklif edir. Hər bir əməliyyat bu mapping üzərindən rəsmi mühasibatlıq jurnalına düşəcək.
                   </p>
                </div>

                <div className="grid grid-cols-2 gap-6">
                   <div className="space-y-3">
                        <label className="text-[10px] font-black text-slate-400 uppercase italic tracking-widest">Anbar (Ehtiyat) Hesabı</label>
                        <select 
                          value={formData.inventoryAccountId}
                          onChange={e => setFormData({...formData, inventoryAccountId: e.target.value})}
                          className="w-full p-5 bg-slate-50 dark:bg-slate-800 border-none rounded-3xl text-sm font-black italic shadow-inner outline-none"
                        >
                           <option value="">Hesab Seçin...</option>
                           <option value="201">201 - Xammal və Materiallar</option>
                           <option value="204">204 - Yarımfabrikatlar</option>
                           <option value="205">205 - Hazır Məhsullar</option>
                        </select>
                   </div>

                   <div className="space-y-3">
                      <label className="text-[10px] font-black text-slate-400 uppercase italic tracking-widest">Gəlir Hesabı</label>
                      <select 
                        value={formData.revenueAccountId}
                        onChange={e => setFormData({...formData, revenueAccountId: e.target.value})}
                        className="w-full p-5 bg-slate-50 dark:bg-slate-800 border-none rounded-3xl text-sm font-black italic shadow-inner outline-none"
                      >
                         <option value="">Hesab Seçin...</option>
                         <option value="601">601 - Satış Gəlirləri</option>
                      </select>
                   </div>

                   <div className="space-y-3">
                      <label className="text-[10px] font-black text-slate-400 uppercase italic tracking-widest">Maya Dəyəri (Xərc) Hesabı</label>
                      <select 
                        value={formData.cogsAccountId}
                        onChange={e => setFormData({...formData, cogsAccountId: e.target.value})}
                        className="w-full p-5 bg-slate-50 dark:bg-slate-800 border-none rounded-3xl text-sm font-black italic shadow-inner outline-none"
                      >
                         <option value="">Hesab Seçin...</option>
                         <option value="701">701 - Satılmış Malların Maya Dəyəri</option>
                         <option value="711">711 - Kommersiya Xərcləri</option>
                      </select>
                   </div>

                   <div className="space-y-3">
                      <label className="text-[10px] font-black text-slate-400 uppercase italic tracking-widest">ƏDV Hesabı</label>
                      <select className="w-full p-5 bg-slate-50 dark:bg-slate-800 border-none rounded-3xl text-sm font-black italic shadow-inner outline-none">
                         <option value="521">521 - Büdcəyə borclar (ƏDV)</option>
                         <option value="241">241 - Vergi üzrə debitor borclar</option>
                      </select>
                   </div>
                </div>
              </div>
            )}

           {activeTab === 'INVENTORY' && (
             <div className="space-y-8 animate-in fade-in duration-300">
                <div className="grid grid-cols-2 gap-8">
                   <div className="space-y-3">
                      <label className="text-[10px] font-black text-rose-500 uppercase italic tracking-widest">Maya Dəyəri Metodu</label>
                      <select 
                        value={formData.costingMethod}
                        onChange={e => setFormData({...formData, costingMethod: e.target.value})}
                        className="w-full p-5 bg-rose-50/50 dark:bg-slate-800 border-none rounded-3xl text-sm font-black italic shadow-inner outline-none focus:ring-2 focus:ring-rose-500/20"
                      >
                         <option value="AVCO">AVCO (Ağırlıqlı Orta Dəyər)</option>
                         <option value="FIFO">FIFO (First In First Out)</option>
                         <option value="LIFO">LIFO (Last In First Out)</option>
                      </select>
                   </div>

                   <div className="space-y-3">
                      <label className="text-[10px] font-black text-slate-400 uppercase italic tracking-widest">Valyuta</label>
                      <select 
                        value={formData.currency}
                        onChange={e => setFormData({...formData, currency: e.target.value})}
                        className="w-full p-5 bg-slate-50 dark:bg-slate-800 border-none rounded-3xl text-sm font-black italic shadow-inner outline-none"
                      >
                         <option>AZN</option>
                         <option>USD</option>
                         <option>EUR</option>
                         <option>TRY</option>
                      </select>
                   </div>
                </div>

                <div className="p-8 bg-slate-900 text-white rounded-[2.5rem] shadow-xl relative overflow-hidden group">
                    <div className="relative z-10">
                        <h4 className="text-[10px] font-black uppercase text-indigo-400 italic mb-4">Stok Davranışı</h4>
                        <div className="space-y-4">
                            <div className="flex items-center justify-between">
                                <span className="text-sm font-black italic">Avtomatik Maya Dəyəri Hesablansın?</span>
                                <div className="w-12 h-6 bg-emerald-500 rounded-full relative"><div className="absolute right-1 top-1 w-4 h-4 bg-white rounded-full"></div></div>
                            </div>
                        </div>
                    </div>
                </div>
             </div>
           )}

           {activeTab === 'PROJECT' && (
             <div className="space-y-8 animate-in fade-in duration-300">
                <div className="grid grid-cols-2 gap-8">
                   <div className="space-y-3">
                      <label className="text-[10px] font-black text-slate-400 uppercase italic tracking-widest">Aida Olduğu Layihə</label>
                      <select className="w-full p-5 bg-slate-50 dark:bg-slate-800 border-none rounded-3xl text-sm font-black italic shadow-inner outline-none">
                         <option value="">Layihə Seçin...</option>
                         <option>Baku Tower Tikintisi</option>
                         <option>Port Baku Residence Phase 2</option>
                      </select>
                   </div>

                   <div className="space-y-3">
                      <label className="text-[10px] font-black text-slate-400 uppercase italic tracking-widest">İşin Növü</label>
                      <select 
                        value={formData.workType}
                        onChange={e => setFormData({...formData, workType: e.target.value})}
                        className="w-full p-5 bg-slate-50 dark:bg-slate-800 border-none rounded-3xl text-sm font-black italic shadow-inner outline-none"
                      >
                         <option>Beton İşləri</option>
                         <option>Suvaq / Boya</option>
                         <option>Elektrik Montajı</option>
                         <option>Torpaq İşləri</option>
                      </select>
                   </div>

                   <div className="space-y-3">
                      <label className="text-[10px] font-black text-slate-400 uppercase italic tracking-widest">Smeta Kodu</label>
                      <input 
                        value={formData.smetaCode}
                        onChange={e => setFormData({...formData, smetaCode: e.target.value})}
                        className="w-full p-5 bg-slate-50 dark:bg-slate-800 border-none rounded-3xl text-sm font-black italic shadow-inner outline-none focus:ring-2 focus:ring-indigo-500/10" 
                        placeholder="Məs: SMK-001/A"
                      />
                   </div>
                </div>
             </div>
           )}

           {activeTab === 'CODE_QR' && (
              <div className="space-y-10 animate-in fade-in duration-300 pb-10">
                <div className="grid grid-cols-2 gap-10">
                  {/* BARCODE SECTION */}
                  <div className="space-y-6">
                    <div className="flex items-center justify-between">
                       <label className="text-[10px] font-black text-slate-400 uppercase italic tracking-widest flex items-center">
                          <Barcode className="w-3.5 h-3.5 mr-2" /> Barkod (Code 128)
                       </label>
                       <button 
                        onClick={() => {
                          const val = formData.sku || `BC-${Math.random().toString(36).substr(2, 9).toUpperCase()}`;
                          setFormData({...formData, barcodeValue: val, isAutoGeneratedCode: true});
                        }}
                        className="text-[9px] font-black text-indigo-600 uppercase italic hover:underline"
                       >
                         Avtomatik Yarat
                       </button>
                    </div>
                    <input 
                      value={formData.barcodeValue}
                      onChange={e => setFormData({...formData, barcodeValue: e.target.value, isAutoGeneratedCode: false})}
                      className="w-full p-5 bg-slate-50 dark:bg-slate-800 border-none rounded-3xl text-sm font-black italic shadow-inner outline-none focus:ring-4 focus:ring-indigo-500/5 transition-all" 
                      placeholder="Barkod dəyəri..."
                    />
                    <div className="p-6 bg-slate-50 dark:bg-slate-800/50 border border-dashed border-slate-200 dark:border-slate-700 rounded-[2rem] flex items-center justify-center min-h-[140px] shadow-inner">
                        {formData.barcodeValue ? (
                          <BarcodePreview value={formData.barcodeValue} />
                        ) : (
                          <div className="text-center">
                            <Barcode className="w-8 h-8 text-slate-200 mx-auto mb-2" />
                            <span className="text-[10px] font-black text-slate-300 uppercase italic">Barkod Daxil Edilməyib</span>
                          </div>
                        )}
                    </div>
                  </div>

                  {/* QR CODE SECTION */}
                  <div className="space-y-6">
                    <div className="flex items-center justify-between">
                       <label className="text-[10px] font-black text-slate-400 uppercase italic tracking-widest flex items-center">
                          <QrCode className="w-3.5 h-3.5 mr-2" /> QR Kod
                       </label>
                       <button 
                        onClick={() => {
                          const val = formData.sku || `QR-${Math.random().toString(36).substr(2, 9).toUpperCase()}`;
                          setFormData({...formData, qrCodeValue: val});
                        }}
                        className="text-[9px] font-black text-indigo-600 uppercase italic hover:underline"
                       >
                         Avtomatik Yarat
                       </button>
                    </div>
                    <input 
                      value={formData.qrCodeValue}
                      onChange={e => setFormData({...formData, qrCodeValue: e.target.value})}
                      className="w-full p-5 bg-slate-50 dark:bg-slate-800 border-none rounded-3xl text-sm font-black italic shadow-inner outline-none focus:ring-4 focus:ring-indigo-500/5 transition-all" 
                      placeholder="QR kod məzmunu..."
                    />
                    <div className="p-6 bg-slate-50 dark:bg-slate-800/50 border border-dashed border-slate-200 dark:border-slate-700 rounded-[2rem] flex items-center justify-center min-h-[140px] shadow-inner">
                        {formData.qrCodeValue ? (
                          <div className="p-4 bg-white rounded-2xl shadow-sm">
                            <QRCodeSVG value={formData.qrCodeValue} size={100} />
                          </div>
                        ) : (
                          <div className="text-center">
                            <QrCode className="w-8 h-8 text-slate-200 mx-auto mb-2" />
                            <span className="text-[10px] font-black text-slate-300 uppercase italic">QR Daxil Edilməyib</span>
                          </div>
                        )}
                    </div>
                  </div>
                </div>

                <div className="p-8 bg-gradient-to-br from-indigo-600 to-indigo-700 text-white rounded-[2.5rem] shadow-2xl shadow-indigo-500/30 flex items-center justify-between relative overflow-hidden group">
                    <div className="absolute top-0 right-0 p-8 opacity-10 group-hover:scale-110 transition-transform">
                        <Printer className="w-24 h-24" />
                    </div>
                    <div className="relative z-10">
                        <h4 className="text-sm font-black uppercase italic mb-1 flex items-center">
                           <Info className="w-4 h-4 mr-2" /> Etiket Çapı
                        </h4>
                        <p className="text-[11px] opacity-80 italic font-bold max-w-sm">Barkod və ya QR kodu stiker kimi çap edə bilərsiniz. Sistem 50x30mm standart etiket ölçüsünə uyğunlaşdırılıb.</p>
                    </div>
                    <button 
                      onClick={() => window.print()}
                      className="relative z-10 bg-white text-indigo-600 px-10 py-4 rounded-[1.5rem] text-[11px] font-black uppercase italic flex items-center space-x-2 hover:bg-slate-50 transition-all shadow-lg active:scale-95"
                    >
                      <Printer className="w-4 h-4" />
                      <span>İndi Çap Et</span>
                    </button>
                </div>
              </div>
           )}
        </div>

        {/* MODAL FOOTER */}
        <div className="px-10 py-8 border-t border-slate-100 dark:border-slate-800 bg-white dark:bg-slate-900 flex justify-between items-center">
           <div>
              {item && (
                <button 
                  onClick={async () => {
                    if (window.confirm('Bu nomenklaturanı silmək istədiyinizə əminsiniz?')) {
                      await inventoryApi.deleteItem(item.id, activeCompany!.id);
                      onSave();
                    }
                  }}
                  className="px-6 py-4 text-rose-500 font-black text-[11px] uppercase tracking-widest hover:text-rose-700 transition-all italic underline underline-offset-8"
                >
                  Nomenklaturanı Sil
                </button>
              )}
           </div>
           <div className="flex items-center space-x-4">
              <button 
                onClick={onClose}
                className="px-10 py-4 text-slate-500 font-black text-[11px] uppercase tracking-widest hover:text-slate-800 transition-all italic underline underline-offset-8"
              >
                Ləğv Et
              </button>
              <button 
                onClick={handleSave}
                disabled={isLoading}
                className="px-16 py-4 bg-indigo-600 text-white hover:bg-indigo-700 rounded-[2rem] font-black text-xs uppercase tracking-[0.2em] shadow-2xl shadow-indigo-600/30 active:scale-95 transition-all flex items-center space-x-3 italic"
              >
                {isLoading ? <span className="animate-spin w-5 h-5 border-2 border-white/30 border-t-white rounded-full"></span> : <Save className="w-5 h-5" />}
                <span>{item ? 'Dəyişiklikləri Saxla' : 'Nomenklaturanı Onayla'}</span>
              </button>
           </div>
        </div>

      </div>
    </div>
  );
};

const BarcodePreview = ({ value }: { value: string }) => {
  const svgRef = useRef<SVGSVGElement>(null);
  
  useEffect(() => {
    if (svgRef.current && value) {
      try {
        JsBarcode(svgRef.current, value, {
          format: "CODE128",
          width: 2,
          height: 60,
          displayValue: true,
          fontSize: 14,
          margin: 10,
          background: "transparent",
          lineColor: "#6366f1"
        });
      } catch (err) {
        console.error("Barcode Generation Error:", err);
      }
    }
  }, [value]);

  return <svg ref={svgRef}></svg>;
};

export default NomenclatureMasterCard;
